//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebexTeams.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebexTeams {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebexTeams() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebexTeams.Properties.WebexTeams", typeof(WebexTeams).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Access Token과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AccessToken {
            get {
                return ResourceManager.GetString("AccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input your webex teams API token here과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AccessTokenDesc {
            get {
                return ResourceManager.GetString("AccessTokenDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List Rooms과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ActivityNameListRooms {
            get {
                return ResourceManager.GetString("ActivityNameListRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ActivityNameSendMessage {
            get {
                return ResourceManager.GetString("ActivityNameSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Webex Teams API Server&apos;s HTTP Status Code 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorCodeDesc {
            get {
                return ResourceManager.GetString("ErrorCodeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Webex Team API Error Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorMessageDesc {
            get {
                return ResourceManager.GetString("ErrorMessageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Local File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LocalFile {
            get {
                return ResourceManager.GetString("LocalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input your local file here 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LocalFileDesc {
            get {
                return ResourceManager.GetString("LocalFileDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input your message here과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MessageDesc {
            get {
                return ResourceManager.GetString("MessageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewMessage {
            get {
                return ResourceManager.GetString("NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created New Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewMessageDesc {
            get {
                return ResourceManager.GetString("NewMessageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Room Id과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RoomId {
            get {
                return ResourceManager.GetString("RoomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input your Room Id here과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RoomIdDesc {
            get {
                return ResourceManager.GetString("RoomIdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Room List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RoomList {
            get {
                return ResourceManager.GetString("RoomList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List of Room name and id과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RoomListDesc {
            get {
                return ResourceManager.GetString("RoomListDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Either {0} or {1} must be given as Input 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ValidateErrorDesc {
            get {
                return ResourceManager.GetString("ValidateErrorDesc", resourceCulture);
            }
        }
    }
}
